name: Install project dependencies
description: Install project dependencies

inputs:
  python-version:
    description: The python version to use
    required: true
  os:
    description: The OS to run on
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      shell: bash
      run: python -m pip install poetry

    - name: Determine poetry version
      shell: bash
      run: echo "{VERSION}=$(poetry --version)"
      id: poetry_version

    - name: Cache poetry.lock
      uses: actions/cache@v4
      with:
        path: poetry.lock
        key: ${{ inputs.os }}-${{ inputs.python-version }}-poetry-${{ steps.poetry_version.outputs.VERSION }}-${{ hashFiles('pyproject.toml') }}

    - name: Install HDF5 (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y libhdf5-dev

    - name: Install HDF5 (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install hdf5
        echo "HDF5_DIR=$(brew --prefix hdf5)" >> "$GITHUB_ENV"

    - name: Install HDF5 (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: choco install hdf5-hdf5lib -y --no-progress

    - name: Install project dependencies
      shell: bash
      run: poetry install -vvv --no-root
