name: Comment Commands
on:
  issue_comment:
    types: created

permissions:
  contents: read

jobs:
  nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: (github.event.issue.pull_request) && github.event.comment.body == '/nightly'

    steps:
      - uses: actions/checkout@v3

      - name: Install project dependencies
        uses: ./.github/setup
        with:
          os: ubuntu-latest
          python-version: "3.11"

      - name: Run pytest (against pandas nightly)
        run: poetry run poe pytest --nightly

  mypy_nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: (github.event.issue.pull_request) && github.event.comment.body == '/mypy_nightly'

    steps:
      - uses: actions/checkout@v3

      - name: Install project dependencies
        uses: ./.github/setup
        with:
          os: ubuntu-latest
          python-version: "3.11"

      - name: Run mypy tests with mypy nightly
        run: poetry run poe mypy --mypy_nightly

  pyright_strict:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: (github.event.issue.pull_request) && github.event.comment.body == '/pyright_strict'

    steps:
      - uses: actions/checkout@v3

      - name: Install project dependencies
        uses: ./.github/setup
        with:
          os: ubuntu-latest
          python-version: "3.11"

      - name: Run pyright tests with full strict mode
        run: poetry run poe pyright_strict
